import type { Metadata } from "next";

import { archivo } from "@/lib/util/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Plagiarism Checker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className}`}>
        {children}
      </body>
    </html>
  );
}
